<?php
// constants.php file returd default configuration setting.
return [
    'status_error_code' => 400,
    'base_URL' => 'https://thecultivist--kandisa21.my.salesforce.com/services/apexrest/',
    'create_lead_API_name' => 'createlead',
    'authorized_token_URL' => 'https://thecultivist--kandisa21.my.salesforce.com/services/oauth2/token',
    'production' => [
        'usd_annual_price_id' => 'plan_Go7csmSqtUz9QH',
        'usd_monthly_price_id' => 'price_1JnNqxDMBMll2GWqikXoKIXX',
        'eur_annual_price_id' => 'price_1J7o4YG3kTPNIyeJ2kXavK8E',
        'eur_monthly_price_id' => 'price_1Jn82sG3kTPNIyeJ7vEzVxgz',
        'gbp_annual_price_id' => 'price_1J7o3jG3kTPNIyeJqj4teox4',
        'gbp_monthly_price_id' => 'price_1Jn82MG3kTPNIyeJJkqk3m9Z',
        'eur_monthly_price_id_dual' => 'price_1JpXvZG3kTPNIyeJHO9xIsYO',
        'eur_annual_price_id_dual' => 'price_1JpXwsG3kTPNIyeJ85eKoaqI',
        'gbp_monthly_price_id_dual' => 'price_1JpXxrG3kTPNIyeJEYS0KB7r',
        'gbp_annual_price_id_dual' => 'price_1JpXxQG3kTPNIyeJpKedKKZY',
        'usd_monthly_price_id_dual' => 'price_1JpXtMDMBMll2GWqVLO0Geqg',
        'usd_annual_price_id_dual' => 'price_1JpXstDMBMll2GWqemyC34Up',
        'usd_annual_price_id_gift' => 'price_1JrQr6DMBMll2GWq6JMcgw1f',
        'gbp_annual_price_id_gift' => 'price_1JrQrmG3kTPNIyeJfS4683TZ',
        'eur_annual_price_id_gift' => 'price_1JrQsDG3kTPNIyeJ5G5zCA1n',
        'salesforce_username' => 'marlies.verhoeven%40thecultivist.com',
        'salesforce_password' => 'Dogdays2018',
        'salesforce_client_id' => '3MVG9szVa2RxsqBaGQzSS2thf6iKy9gGluD2979jniKFXHrc6nc1vZ4OTw_PwoXVQNtWlUf3NE.2H0R08yQKO',
        'salesforce_client_secret' => '20983D576824023C7D59591642B9D98A2104787E157E0E3FA3B5167286835C88',
        'salesforce_token' => 'J3vmtrm6pwcCIAlQttIXuFIS1',
        'salesforce_base_URL' => 'https://thecultivist.my.salesforce.com/services/apexrest/',
        'salesforce_token_url' => 'https://thecultivist.my.salesforce.com/services/oauth2/token'
    ],
    'sandbox' => [
        'usd_annual_price_id' => 'price_1JrQbkDMBMll2GWqIeFLkctN',
        'usd_monthly_price_id' => 'price_1JrQc7DMBMll2GWq9zh3BSXD',
        'eur_annual_price_id' => 'price_1JrQZeG3kTPNIyeJN9ac8Ufm',
        'eur_monthly_price_id' => 'price_1JrQVbG3kTPNIyeJXraPhFZW',
        'gbp_annual_price_id' => 'price_1JrQZAG3kTPNIyeJdKtIW2Wy',
        'gbp_monthly_price_id' => 'price_1JrQW1G3kTPNIyeJPp42uWl6',
        'eur_monthly_price_id_dual' => 'price_1JrQWxG3kTPNIyeJC6BUPHEp',
        'eur_annual_price_id_dual' => 'price_1JrQYIG3kTPNIyeJvlZjf09Q',
        'gbp_monthly_price_id_dual' => 'price_1JrQWbG3kTPNIyeJoZSCBmPu',
        'gbp_annual_price_id_dual' => 'price_1JrQYjG3kTPNIyeJvATU2Poy',
        'usd_monthly_price_id_dual' => 'price_1JrQckDMBMll2GWqlU9Pcd9j',
        'usd_annual_price_id_dual' => 'price_1JrQdBDMBMll2GWqeMDpre6W',
        'usd_annual_price_id_gift' => 'price_1JrQbPDMBMll2GWqku0FVIhC',
        'gbp_annual_price_id_gift' => 'price_1JrQacG3kTPNIyeJEpAbeLBs',
        'eur_annual_price_id_gift' => 'price_1JrQaJG3kTPNIyeJoFICL1i9',
        'salesforce_username' => 'rahul%40kandisatech.com',
        'salesforce_password' => 'Cultivist%4012',
        'salesforce_client_id' => '3MVG9d3kx8wbPieGlphtF5U_r5vE5n6xzmYszuNbcgO_Fl7rWpUfWIUWgbO76BWpB7AbTngUbVJNc8T_IU0yk',
        'salesforce_client_secret' => '223354502D7CD5E90324AA7A777A7104BB034CECF71A0548D30E8D472009EBF5',
        'salesforce_base_URL' => 'https://thecultivist--kandisa21.my.salesforce.com/services/apexrest/',
        'salesforce_token_url' => 'https://thecultivist--kandisa21.my.salesforce.com/services/oauth2/token',
    ],
    'curlopt_httpheader' => [
        'gift_browser_id' => 'tdG2nKgDEeu56Q1Yr4wGvQ',
        'individual_dual_browser_id' => 'bPUO05dxEeusWeWw8fMlDw',
    ],
    'app_env' => env('APP_ENV'),
    'payment_status' => [
        'payment_success' => 'Successful',
        'payment_failure' => 'Unsuccessful',
        'renewal_success' => 'Successful',
        'renewal_failure' => 'Unsuccessful'
    ],
    'eur_countries' => ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IS', 'IE', 'IT', 'LV', 'LI', 'LT', 'LU', 'MT', 'MC', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'ES', 'SE', 'CH'],
    'gbp_countries' => ['GB'],
    'currency_symbols' => [
        'USD' => '$',
        'GBP' => '£',
        'EUR' => '€',
    ]
];
